### PR TITLE
Add PHP 7 on Travis

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Looks clear, the fail is related to deprecated stuffs, fixed in #371

**Comment by Soullivaneuh** [comment]
Branch rebased, waiting for Travis.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by stof** [comment]
Can you remove it from allowed failures as tests are passing ?

**Comment by Soullivaneuh** [comment]
@stof done.

**Comment by stof** [comment]
Thank you @Soullivaneuh.

**Comment by TomasVotruba** [comment]
@stof Thansk

**Pull request merged**
