### PR TITLE
bump version since we are in 2.6.1!

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by xabbuh** [comment]
@cordoval Why did you close?

**Comment by cordoval** [comment]
it is too simple :older_man:

**Comment by xabbuh** [comment]
But it wasn't merged yet. :)

**Comment by cordoval** [comment]
I can resend it if they promise to take it in :older_man:

**Comment by stof** [comment]
@cordoval I missed your PR. This is why it was not merged. Please restore your branch to reopen the PR

**Comment by cordoval** [comment]
@stof https://github.com/symfony/AsseticBundle/pull/354

**Pull request closed without merging**
